#include <iostream>

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int main() {
    long int sum = 0;
    long int evenSum = 0;
    long int prev = 0;
    long int current = 1;

    while (sum <= 4000000)
    {
        std::cout << sum << ", " << std::endl;
        prev = current;
        current = sum;
        sum = prev + current;
        if(sum % 2 == 0) {
            evenSum += sum;
        }
    }

    std::cout << evenSum;

    // while (current < 4000000)
    // {
    //     std::cout << prev << " " << current << " " << sum << std::endl;
    //     // if (sum % 2 == 0) {
    //     //     evenSum += sum;
    //     // }
    //     //std::cout << (prev + current) << std::endl;
    //     prev = current;
    //     current = sum;
    //     sum += (prev + current);
    //     //std::cout << prev << " " << current << " " << sum << std::endl;
    // }
    //std::cout << sum << std::endl;

    return 0;
}